### PR TITLE
Support 32-bit values in System Stats

### PR DESCRIPTION
**Pull request by kamiljanowski-silvair**

### CODE REVIEW

**Comment by bartoszflis-silvair** [comment]
There is a problem with dependencies in CI:
```
pkg_resources.ContextualVersionConflict: (coverage 6.0b1 (/home/travis/build/SilvairGit/python-bluetooth-mesh/.eggs/coverage-6.0b1-py3.7-linux-x86_64.egg), Requirement.parse('coverage<6.0,>=4.1'), {'coveralls'})
```

**Comment by kamiljanowski-silvair** [comment]
@bartoszflis-silvair It's connected with my PR? I didn't add any new imports.

**Comment by bartoszflis-silvair** [comment]
@kamiljanowski-silvair Don't know yet.

**Comment by kamiljanowski-silvair** [comment]
@bartoszflis-silvair Added requirement for `coverage` version. It's strange, but it looks like it took newest version of coverage due to requirement of previous package, and then raise conflict when it meet the `coverage=<6.0.0` requirement. Force `coverage=<6.0.0` in our package fix this behavior.

**Review by michallowasrzechonek-silvair — APPROVED** [review]

**Pull request merged**
